# Generated by Django 2.1.7 on 2019-03-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('channel', models.CharField(max_length=40, null=True)),
                ('country', models.CharField(max_length=2, null=True)),
                ('os', models.CharField(choices=[(1, 'android'), (2, 'ios')], max_length=7, null=True)),
                ('impressions', models.PositiveIntegerField(null=True)),
                ('clicks', models.PositiveIntegerField(null=True)),
                ('installs', models.PositiveIntegerField(null=True)),
                ('spend', models.FloatField(null=True)),
                ('revenue', models.FloatField(null=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
